version: "3"

services:
  wireguard_cli:
    image: linuxserver/wireguard:1.0.20210914-alpine
    container_name: wg-3p.wireguard_cli.1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - LOG_CONFS=true #optional
    ports:
      - 8080:8080 #socks5 port 3proxy
      - 1080:1080 #admin port 3proxy
      - 3129:3129 #http port 3proxy
    volumes:
      - "./wireguard/config:/config:ro" #wireguard config dir wg0.conf
      - "/lib/modules:/lib/modules:ro" #optional
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped #optional
  3proxy:
    image: 3proxy/3proxy:0.9.4
    container_name: wg-3p.3proxy.1
    volumes:
      - "./3proxy/config/conf:/usr/local/3proxy/conf:ro" #3proxy config dir
    network_mode: "service:wireguard_cli"
    restart: unless-stopped #optional
